import { Geist } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/component/Navbar/page";
import FooterPage from "@/component/Footer/page";
import ToastProvider from "@/component/ToastProvider/page";
import Providers from "./lib/Provider";
import Provider from "./lib/Provider";

const geist = Geist({
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "keen-keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geist.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <NavbarPage />
          {children}
          <ToastProvider />
          <FooterPage />
        </Provider>
      </body>
    </html>
  );
}
