import { Geist } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/component/Navbar/page";
import FooterPage from "@/component/Footer/page";

const geist = Geist({
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "keen-keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geist.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavbarPage />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
